config/routes.rb
Rails.application.routes.draw do
  resources :remedies, only: [:create, :new, :show]

  root 'home#home'
  get 'hurray' => 'home#hurray'

end

app/models/remedy.rb
class Remedy < ActiveRecord::Base
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @background_color = ["#40E0D0", "#87CEFA", "#7B68EE","#EE82EE","#4682B4", "#6495ED","#DAA520","#FF6347","#FFA500","#3CB371","#20B2AA"].sample
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
    @hiccup_cure = ["Take seven smalls sips of something.",
      "Eat a small piece of dark chocolate.",
      "Take little sips of water and say mamae after each one. It must be water and it must be ma mae... not mommy or anything else.",
      "What did you eat for lunch yesterday?",
      "Pull out your tongue with both hands.",
      "Have someone ask you stupid questions.",
      "Breath into a paper bag.",
      "Boo!",
      "Exhale... now hold your breath and count to ten.",
      "Chug a glass of water.",
      "Drink water with a spoon on your nose.",
      "Drink water from the wrong side of the glass (upside down).",
      "Take sips of water, but do not swallow. Tip your head back, plug your nose, now swallow. Repeat this 3x.",
      "Eat a spoonfull of sugar, honey, or peanut butter.",
      "Squeeze your pinky finger.",
      "Squeeze the pressure point of your non-dominant hand.",
      "Pinch your shoulder.",
      "Recite the alphabet backwards.",
      "Massage the soft palate of your mouth."].sample
  end

  def hurray
  end

end

app/controllers/remedies_controller.rb
class RemediesController < ApplicationController
  before_action :set_remedy, only:[:show]

  def show
  end

  def index
    @remedies = Remedy.all
  end

  def new
    @remedy = Remedy.new
  end

  def create
    @remedy = Remedy.new(remedy_params)

    respond_to do |format|
      if @remedy.save
        format.html { redirect_to @remedy, notice: 'Remedy was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end



  private

    def set_remedy
      @remedy = Remedy.find(params[:id])
    end

    def remedy_params
      params.require(:remedy).permit(:description, :twitter_handle)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/remedies_helper.rb
module RemediesHelper
end

app/views/home/home.html.erb
<body class="home">
  <div class="home-container">
    <div class="add-remedy">
        <a class="button" href="<%=new_remedy_url %>" title="Add your own remedy"><i class="fa fa-plus fa-2x"></i></a>
    </div>
    <div class="display-remedy-description">
        <h1><%=@hiccup_cure%></h1>
    </div>
    <div>
      <a class="button remedy-didnt-work" href="" title="Hiccup! I need another remedy!"><i class="fa fa-times-circle fa-4x"></i></a>
      <a class="button remedy-worked" href="/hurray" title="It worked!"><i class="fa fa-check-circle fa-4x"></i></a>
    </div>
  </div>
</body>

app/views/home/hurray.html.erb
 <body class="hurray-the-remedy-worked">
  <div>
    <h1>Hurray! No more hiccups!</h1>
    <a class="button" href="https://twitter.com" title="Share it on Twitter!"><i class="fa fa-twitter fa-5x"></i>
  </div>

  <div>
    <a class="button" href="/" title="Home"><i class="fa fa-home fa-2x"></i></i>
  </div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hiccup Helper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body style="background-color:<%=@background_color%>">
    <%= yield %>
  </body>
</html>

app/views/remedies/new.html.erb
<body class="remedy">
  <div class="add-new-remedy-page">
    <h1>What's your remedy?</h1>
    <%= form_for(@remedy) do |f| %>
      <% if @remedy.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@remedy.errors.count, "error") %> prohibited this remedy from being saved:</h2>

          <ul>
          <% @remedy.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="remedy-description-field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>

      <div class="twitter-field">
        <%= f.label :twitter_handle %><br>
        <%= f.text_field :twitter_handle %>
      </div>

      <div class="actions">
        <%= f.submit%>
      </div>

      <div class="home">
        <a href="/" title="Home"><i class="button fa fa-home fa-2x"></i></i>
      </div>

    <% end %>
  </div>
</body>

app/views/remedies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>description:</strong>
  <%= @remedy.description %>
</p>

<p>
  <strong>twitter handle:</strong>
  <%= @remedy.twitter_handle %>
</p>

<%= link_to 'Back', new_remedy_url %>

<div>
  <a class="button" href="/" title="Home"><i class="fa fa-home fa-2x"></i></i>
</div>